name: VulnCheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.20.6
           go-package: ./...
